name = 'pipelined_adder'
description = 'Example VHDL design'
language.vhdl.standard = 2008

[rtl]
sources = ['pipelined_adder.vhdl']
top = 'pipelined_adder'
clock_port = 'clock'

[tb]
sources = ['pipelined_adder_tb.vhdl']
top = 'pipelined_adder_tb'
uut = 'uut'

[flow.openroad]
platform = "sky130hd"
clocks.main_clock.freq = "200 MHz"
core_utilization = 45
