import logging
from typing import Optional

from ..board import WithFpgaBoardSettings, get_board_data
from ..dataclass import Field, field_validator, model_validator
from ..flow import FlowSettingsException, FpgaSynthFlow, propagate_to_dependency
from ..tool import Tool
from .nextpnr import Nextpnr

__all__ = ["Openfpgaloader"]

log = logging.getLogger(__name__)


class Openfpgaloader(FpgaSynthFlow):
    """Build a bitstream and program it onto an FPGA board with openFPGALoader.

    Runs the full `yosys_fpga` -> `nextpnr` chain, packs the routed design into a bitstream
    (e.g. with `ecppack` for ECP5), and loads it over the configured `cable` or `board`. This is
    the only flow that touches real hardware.
    """

    # This flow reports no results beyond the keys every flow reports; declaring this
    # explicitly keeps `xeda list-results` from guessing.
    results_description: dict = {}

    ofpga_loader = Tool("openFPGALoader")

    class Settings(WithFpgaBoardSettings):
        clock_period: float = Field(
            description="Target clock period in nanoseconds, passed to the synthesis and place & "
            "route dependencies."
        )
        reset: bool = Field(
            False, description="Reset the FPGA after loading the bitstream (`--reset`)."
        )
        cable: Optional[str] = Field(
            None,
            description='Programming cable to use, e.g. "ft2232". Takes precedence over the '
            "cable implied by `board`.",
        )
        nextpnr: Optional[Nextpnr.Settings] = Field(
            None,
            description="Settings for the `nextpnr` dependency that places and routes the design.",
        )

        @field_validator("nextpnr", mode="before")
        @classmethod
        def _validate_nextpnr(cls, value, info):
            values = info.data if isinstance(info.data, dict) else {}
            clocks = values.get("clocks")
            fpga = values.get("fpga")
            board = values.get("board")
            if value is None:
                value = {}
            if isinstance(value, Nextpnr.Settings):
                value = value.model_dump()
            assert isinstance(value, (dict)), f"not a dict: {value}"
            value["fpga"] = fpga
            value["board"] = board
            value["clocks"] = clocks
            return Nextpnr.Settings(**value)

        @model_validator(mode="after")
        def _sync_nextpnr_dependency(self, info):
            """Keep the `nextpnr` dependency's target and constraints in step with ours.

            The `before` validator above only runs when `nextpnr` itself is validated, so
            without this an `openfpgaloader.fpga = ...` assignment left the dependency
            placing and routing for the previous device.
            """
            if self.nextpnr is not None and info.field_name in (
                None,
                "nextpnr",
                "fpga",
                "board",
                "clocks",
                "clock_period",
            ):
                propagate_to_dependency(self.nextpnr, self, "fpga", "board", "clocks")
            return self

    def init(self) -> None:
        self.packer: Optional[Tool] = None
        assert isinstance(self.settings, self.Settings)
        ss = self.settings
        assert ss.nextpnr is not None
        self.add_dependency(Nextpnr, ss.nextpnr)
        if ss.fpga is None:
            raise FlowSettingsException("")
        if ss.fpga.family == "ecp5":  # FIXME from fpga/board
            self.packer = Tool("ecppack")

    def run(self) -> None:
        assert isinstance(self.settings, self.Settings)
        ss = self.settings
        board_id = ss.board
        board_name = None
        if board_id:
            board_data = get_board_data(board_id)
            if board_data:
                board_name = board_data.get("name")
        next_pnr = self.completed_dependencies[0]
        assert isinstance(next_pnr, Nextpnr)
        assert isinstance(next_pnr.settings, Nextpnr.Settings)
        assert next_pnr.settings.textcfg
        text_cfg = next_pnr.run_path / next_pnr.settings.textcfg
        assert text_cfg.exists(), f"Can't find {text_cfg} generated by Nextpnr!"
        bitstream = f"{board_name}.bit" if board_name else "bitstream.bit"
        if self.packer:
            self.packer.run(text_cfg, bitstream)
        args = ["--bitstream", bitstream]
        if ss.cable:
            args.extend(["--cable", ss.cable])
        elif board_name:
            args.extend(["--board", board_name])
        assert ss.fpga is not None
        if ss.fpga.part:
            args.extend(["--fpga-part", ss.fpga.part])
        if ss.reset:
            args.append("--reset")
        if ss.verbose:
            args.append("--verbose")
        self.ofpga_loader.run(*args)
