
## Automatically generated by Xeda
## ISE 14.7

puts "\n==============================( Creating Project )================================"
if { [catch  { project new {{design.name|tcl_word}} }] } {
    project open {{design.name|tcl_word}}
}
{% if settings.fpga.family %}
project set family {{settings.fpga.family|tcl_word}}
{% endif %}
{% if settings.fpga.device %}
project set device {{settings.fpga.device|tcl_word}}
{% endif %}
{% if settings.fpga.package %}
project set package {{settings.fpga.package|tcl_word}}
{% endif %}
{% if settings.fpga.speed %}
project set speed {{("-" ~ settings.fpga.speed)|tcl_word}}
{% endif %}

project set "Generate Detailed MAP Report" TRUE


puts "\n==============================( Adding RTL Sources )================================"
{% for src in source_files|default(sources_read()) %}
xfile add {{src|tcl_word}} -copy
{%- endfor %}
{% if source_include_dirs|default([]) %}
project set "Verilog Include Directories" {{source_include_dirs|map('string')|join(' ')|tcl_word}} -process "Synthesize - XST"
{% endif %}

project set top {{design.rtl.top|tcl_word}}

puts "\n==============================( Adding Constraint Files )================================"
{% for ucf_file in settings.ucf_files %}
if { [catch  { xfile add {{ucf_file|tcl_word}} }] } {
    puts "unable to add {{ucf_file|tcl_quote}}"
}
{% endfor %}

{% if settings.xcf_file %}
project set "Use Synthesis Constraints File" TRUE
project set "Synthesis Constraints File" {{settings.xcf_file|tcl_word}}
{% endif %}

# puts [project properties] # to see the full list of properties

puts "\n==============================( Setting Options )================================"
{% if settings.nthreads is not none %}
project set "Enable Multi-Threading" {{2 if settings.nthreads and settings.nthreads > 1 else "Off"}} -process "MAP"
project set "Enable Multi-Threading" {{[settings.nthreads, 4]|min if settings.nthreads and settings.nthreads > 1 else "Off"}} -process "Place & Route"
{% endif %}

{% for k, v in settings.translate_options.items() %}
project set {{k|tcl_word}} {{format_value(v)}} -process "Translate"
{% endfor %}
{% for k, v in settings.synthesis_options.items() %}
project set {{k|tcl_word}} {{format_value(v)}} -process "Synthesize - XST"
{% endfor %}
{% for k, v in settings.map_options.items() %}
project set {{k|tcl_word}} {{format_value(v)}} -process "Map"
{% endfor %}
{% for k, v in settings.pnr_options.items() %}
project set {{k|tcl_word}} {{format_value(v)}} -process "Place & Route"
{% endfor %}
{% for k, v in settings.trace_options.items() %}
project set {{k|tcl_word}} {{format_value(v)}} -process "Generate Post-Place & Route Static Timing"
{% endfor %}


# `process run` reports a failed process only by its result and the process status: it raises no
# TCL error, so xtclsh would exit 0 after a failed run. Check both, as ISE's own generated scripts
# do, and exit 1 on failure.
proc run_ise_process {name} {
    set result [process run $name]
    set status [process get $name status]
    if {!$result || ($status ne "up_to_date" && $status ne "warnings")} {
        puts stderr "ISE process \"$name\" failed (status: $status)"
        exit 1
    }
}

puts "\n==============================( Implementing Design )================================"
run_ise_process "Implement Design"

puts "\n==============================( Generating Programming File )================================"
run_ise_process "Generate Programming File"

# project close
