# © 2022-2025 [Kamyar Mohajerani](mailto:kammoh@gmail.com)
"""Installable agent skill: instructions plus a reference generated from the installed version.

The prose lives in `xeda/data/agent/` and ships with the package. The flow catalog is generated
from live introspection at install time, so it can never drift from the version that is actually
installed -- the failure mode a hand-maintained catalog always eventually has.
"""

from __future__ import annotations

import logging
import shutil
from contextlib import contextmanager
from pathlib import Path
from typing import Dict, Iterator, List, Optional

from importlib_resources import as_file, files

from .introspect import flows_info, results_info, settings_info

log = logging.getLogger(__name__)

__all__ = [
    "SKILL_NAME",
    "generate_flows_reference",
    "install_skill",
    "skill_source_dir",
]

SKILL_NAME = "xeda"

#: Order categories are presented in, most commonly used first.
_CATEGORY_ORDER = ["simulation", "fpga_synthesis", "asic_synthesis", "synthesis", "other"]
_CATEGORY_TITLES = {
    "simulation": "Simulation",
    "fpga_synthesis": "FPGA synthesis / implementation",
    "asic_synthesis": "ASIC synthesis",
    "synthesis": "Synthesis (generic)",
    "other": "Other",
}


@contextmanager
def skill_source_dir() -> Iterator[Path]:
    """Directory holding the packaged skill sources, valid only inside the context.

    A context manager rather than a plain path: when xeda is imported from a zip (or any other
    non-filesystem loader) `as_file` extracts the resources to a temporary directory and deletes
    it on exit, so a path returned from inside the `with` names something that no longer exists.
    Keeping the context open for as long as the caller reads the files is the only safe shape.
    """
    with as_file(files("xeda.data").joinpath("agent")) as path:
        yield Path(path)


def _flow_section(flow: Dict[str, object]) -> str:
    name = str(flow["name"])
    lines = [f"### `{name}`", ""]

    facts: List[str] = []
    aliases = flow.get("aliases") or []
    if isinstance(aliases, list) and aliases:
        facts.append("aliases: " + ", ".join(f"`{a}`" for a in aliases))
    deps = flow.get("dependencies") or []
    if isinstance(deps, list) and deps:
        facts.append("runs first: " + " -> ".join(f"`{d}`" for d in deps))
    if flow.get("supports_cocotb"):
        facts.append("supports cocotb testbenches")
    if facts:
        lines += ["*" + " | ".join(facts) + "*", ""]

    description = flow.get("description")
    if description:
        lines += [" ".join(str(description).split()), ""]

    settings = settings_info(name)
    specific = [f for f in settings["fields"] if not f.get("common")]
    required = [f["name"] for f in specific if f.get("required")]
    if required:
        lines += ["Required settings: " + ", ".join(f"`{r}`" for r in required), ""]
    lines += [
        f"{len(specific)} flow-specific settings "
        f"(plus the common ones): `xeda list-settings {name} --json`",
        "",
    ]

    results = results_info(name)
    keys = [k["name"] for k in results["keys"] if not k["common"]]
    if keys:
        lines += ["Reports: " + ", ".join(f"`{k}`" for k in keys), ""]
    elif results["documented"]:
        lines += ["Reports no results beyond the keys every flow reports.", ""]
    return "\n".join(lines)


def generate_flows_reference() -> str:
    """Markdown catalog of every flow in the installed version of xeda."""
    flows = flows_info()
    out = [
        "# Flow catalog",
        "",
        "Generated by `xeda skill install` from the installed version of xeda. Regenerate after "
        "upgrading xeda, or when a flow is added.",
        "",
        "Settings are deliberately not listed here (there are several hundred). For any flow:",
        "",
        "```bash",
        "xeda list-settings <flow> --json     # every setting: name, type, default, meaning",
        "xeda list-results <flow> --json      # every result key, with its meaning",
        "```",
        "",
    ]

    by_category: Dict[str, List[Dict[str, object]]] = {}
    for flow in flows:
        by_category.setdefault(str(flow["category"]), []).append(flow)

    for category in _CATEGORY_ORDER + sorted(set(by_category) - set(_CATEGORY_ORDER)):
        group = by_category.get(category)
        if not group:
            continue
        out += [f"## {_CATEGORY_TITLES.get(category, category)}", ""]
        out += [_flow_section(flow) for flow in group]
    return "\n".join(out).rstrip() + "\n"


def install_skill(dest_dir: Path, force: bool = False) -> List[Path]:
    """Write the skill into `dest_dir/xeda/`, regenerating the flow catalog.

    Returns the paths written. Refuses to overwrite an existing installation unless `force`.
    """
    target = Path(dest_dir) / SKILL_NAME
    if target.exists() and not force:
        raise FileExistsError(
            f"{target} already exists. Pass --force to overwrite it, or choose another --dir."
        )
    written: List[Path] = []

    (target / "references").mkdir(parents=True, exist_ok=True)
    # Copy while the resource context is open: the sources may live in a temporary directory
    # that only exists for the duration of the `with`.
    with skill_source_dir() as source:
        shutil.copyfile(source / "SKILL.md", target / "SKILL.md")
        written.append(target / "SKILL.md")
        for reference in sorted((source / "references").glob("*.md")):
            shutil.copyfile(reference, target / "references" / reference.name)
            written.append(target / "references" / reference.name)

    flows_md = target / "references" / "flows.md"
    flows_md.write_text(generate_flows_reference(), encoding="utf-8")
    written.append(flows_md)
    return written


def default_skill_dir(start: Optional[Path] = None) -> Path:
    """Where to install by default: `.claude/skills` under the current directory."""
    return (start or Path.cwd()) / ".claude" / "skills"
